[forest]
trees = ["test" ]                   # The directories in which your trees are stored
url   = "https://localhost:8080/"
home  = "basic-macros"
assets = ["assets"]                  # The directories in which your assets are stored
# theme = "theme"                      # The directory in which your theme is stored
# stylesheet = "forest.xsl"
